version: 2.1

workflows:
  build:
    jobs:
      - build_edxapp_image:
          filters:
            branches:
              only: Jhony/circleci_tutor


jobs:

  build_edxapp_image:
    docker:
      - image: edxops/focal-common:latest
    steps:

      - run:
          name: Prepare tutor environment
          command: |
            mkdir -p /tmp/tutor_build /tmp/tutor_build/tutor_root/tutor
            cd /tmp/tutor_build
            echo -e "export TUTOR_ROOT=/tmp/tutor_build/tutor_root/tutor\nexport TUTOR_PLUGINS_ROOT=/tmp/tutor_build/tutor_root/tutor-plugins" >> tutor_env
            git clone -b Jhony/namespace_nginx https://github.com/eduNEXT/tutor.git
            virtualenv -p python3.8 /tmp/tutor_build/venv
            source venv/bin/activate
            cd tutor && pip install -e . && cd ..
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone -b Jhony/tutor_namespace git@bitbucket.org:edunext/ednx_tutor_plugins.git tutor_plugins
            ln -s /tmp/tutor_build/tutor_plugins /tmp/tutor_build/tutor_root/tutor-plugins

      - run:
          name: Enable tutor plugins
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            tutor plugins enable ednx_hosts
            tutor plugins enable ednx_secrets
            tutor plugins enable ednx_databases
            tutor plugins enable ednx_forum
            tutor plugins enable ednx_k8s
            tutor plugins enable ednx_docker
            tutor plugins enable ednx_edxapp
            tutor plugins enable ednx_general

      - run:
          name: Creating tutor config
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            tutor plugins list
            tutor config save

      - run:
          name: Setup Bragi theme in tutor
          working_directory: /tmp/tutor_build
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone -b master git@bitbucket.org:edunext/ednx-saas-themes.git
            cd ednx-saas-themes/edx-platform && cp -R bragi /tmp/tutor_build/tutor_root/tutor/env/build/openedx/themes && cd ../..

      - run:
          name: Installing Docker CLI
          command: |
            apt update
            apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt install docker-ce-cli=5:19.03.13~3-0~ubuntu-focal -y

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Building openedx image with tutor
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            priv_repos_key=$(echo -e $SSH_PRIV_REPOS_KEY)
            main_repo_url="<< pipeline.project.git_url >>.git"
            main_repo_branch="<< pipeline.git.branch >>"
            tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=$main_repo_url --build-arg EDX_PLATFORM_VERSION=$main_repo_branch --build-arg edx_platofrm_patches_enabled=False --build-arg SSH_PRIVATE_KEY="$priv_repos_key"
