version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_edxapp_image:
          filters:
            branches:
              only: Jhony/circleci_tutor


jobs:

  build_edxapp_image:
    docker:
      - image: edxops/focal-common:latest
    steps:

      - run:
          name: Prepare tutor environment
          command: |
            mkdir -p /tmp/tutor_build
            cd /tmp/tutor_build
            echo "TUTOR_ROOT=/tmp/tutor_build/tutor_root/tutor\nexport TUTOR_PLUGINS_ROOT=/tmp/tutor_build/tutor_root/tutor-plugins"
            git clone -b Jhony/namespace_nginx https://github.com/eduNEXT/tutor.git
            virtualenv -p python3.8 /tmp/tutor_build/venv
            source venv/bin/activate
            cd tutor && pip install -e . && cd ..
