name: Openedx 2nd batch

on: push

jobs:
  run-tests:
    continue-on-error: true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ["2.2"]
        mongodb-version: ['4.0']
        test_module: [
            "openedx/core/djangoapps/commerce/ openedx/core/djangoapps/common_initialization/ openedx/core/djangoapps/common_views/ openedx/core/djangoapps/config_model_utils/ 
             openedx/core/djangoapps/content/ openedx/core/djangoapps/content_libraries/ openedx/core/djangoapps/contentserver/ openedx/core/djangoapps/cors_csrf/ openedx/core/djangoapps/course_date_signals/"
        ]
        

    name: ${{ matrix.test_module }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Required System Packages
        run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install requirements
        run: |
          pip install --upgrade --force-reinstall -r requirements/pip.txt
          pip install --upgrade --force-reinstall -r requirements/edx/testing.txt
          pip install --exists-action w -r requirements/edunext/base.txt
          pip install "django~=${{ matrix.django-version }}.24"
      
      - name: Run tests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 45
          max_attempts: 3
          retry_on: error
          command: pytest ${{ matrix.test_module }}
